name: Feature Request(功能请求)
description: 提出一个建议或者需要的新功能
labels: enhancement
title: "[FEATURE]"
body:
  - type: checkboxes
    id: search-issue
    attributes:
      label: 是否有重复的issue?
      description: 请搜索以查看您要提交的Feature是否已有重复issue
      options:
        - label: 我已经检索过相关issue
          required: true
  - type: textarea
    id: relate-issue
    attributes:
      label: 这个功能是否与某个问题相关
      description: 简明扼要的描述你遇到的问题
    validations:
      required: true
  - type: textarea
    id: expect-feature
    attributes:
      label: 描述你的期望功能
      description: 简明扼要的描述你希望增加的新功能
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 描述你的替代方案
      description: 简明扼要描述您考虑过的任何替代解决方案或新功能
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其他
    validations:
      required: false
