export const CONFIG = {
  URLS: {
    IMGBOX: 'https://imgbox.com',
    PTPIMG: 'https://ptpimg.me',
    HDB_UPLOAD: 'https://img.hdbits.org/upload_api.php',
    IMGBOX_UPLOAD: 'https://imgbox.com/upload/process',
    PIXHOST_UPLOAD: 'https://pixhost.to/remote/',
    PTPIMG_UPLOAD: 'https://ptpimg.me/upload.php',
    IMGBB: 'https://imgbb.com/json',
  },
  ERROR_MESSAGES: {
    UPLOAD_FAILED: '上传失败，请重试',
    PTPIMG_UPLOAD_FAILED: 'ptpimg上传失败',
    NO_API_KEY: '请到配置面板中填入ptpimg的api_key',
    NO_TRANSFER_NEEDED: '无需转存',
  },
  FILTER_IMGS_NAMES: [
    'poster.jpg',
    '2019/01/04/info.png',
    'MoreScreens',
    'PTer.png',
    'ms.png',
    'trans.gif',
    'PTerREMUX.png',
    'PTerWEB.png',
    'CS.png',
    'Ourbits_info',
    'GDJT',
    'douban',
    'logo',
    '2019/03/28/5c9cb8f8216d7.png',
    '_front',
    'info_01.png',
    'screens.png',
    '04/6b/Ggp5ReQb_o',
    'ce/e7/KCmGFMOB_o',
  ],
};
