url: https://baconbits.org
host: baconbits.org
siteType: gazelle
icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0/AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAC5VBMVEX///9vAAAAAABrAAB5BARsAAB4AgLEzc2/ycmtubnDyMi9w8P///+7d3eZNDSZMzOYMjKhQ0P48vJ6AAB6AAB6AAB6AAB6AACADAxtAACWAAC8AACwAAB5AAB0AQF3AAB6AACAAAB4AgJxAgKUAACjAACFAQF1AgJ4AgJxAgKbAACEBgaJAADwAACbAACNAAB8CQmABweCBgaJAACBAADQAAC8AAB+AACDAADSAACUQ0O+urq/vb3Bw8OriYmVFhaVRUWAAACJAAC6sbHCw8PDx8fDxsbH0dG8uLizlZW6sbGDCQmmenqym5vI2NjEzc3L39+sjIyyoaHI2NjEzc3Ezc3Ezc3Ezc3H09OqhoadY2Oznp7K3d3CyMjCyMjCyMjCyMjCyMjV1dXMzMzd3d29AAC+AAD9AAD/AADjAACZAACAAADEAAD/Bgb+Fxf/Fxf/GBj/EBCMAADJAADaAACBAAD6AAD/NDT/ra3/sLD/r6//tbX/fX39BATxAADyAAD/AQHYAQHYAAD/R0f/l5f/mJj/mZn/f3/rAADXAADZAADzAAD/TU3YaGiBAgKBAQHYRUX/jY3/n5//e3v/enr/eXn/ior/oqL/bm7/aGj/MzP/Rkb/kpLYeXnYgoL/oKD/goL/j4//g4P/sbH/vr7/Nzf/Ojr/PT3/lpb/o6PYVFTYWVn/h4f/lJT/pKT/iIj/gYH/fn7/np7/vb3/vLz/kZHYX1/YV1f/qan/jo7/GRn/ERH/SEj/s7P/hIT/iYn/paXYhYXYhIT/Jib/Dg7/SUn/qqr/mpr/fHz/q6vYJSXYSkr/Nja6AADQAAD+Cwv/Wlr/Zmb/rKz/MDB/AADCEBCQOTmPOjqNPDykKSncAAD/kJD/KSnuAADCERGUOTnRAAC+BgbjAgL3AQH/AgL+AgL3AAC6BgakV1eUFhaLAADGAQH7AACuAACgV1erjY2nRUWiAACiAQGoYmKcYWGcY2P///8ZpM3CAAAAZXRSTlMAAAAAAAAAAAAAAAABAgQEBQMBM6+yuH4CO6j93HIOP4OAAS6n6V9JJS+nIbj++40XHSG74fbw4OH29uHh4On+9vv+uyEdHhZe+LhNza0vARLqpy5cRA5xfr/9qDtZt7KvMwIEAmw4yNkAAAABYktHRACIBR1IAAAAB3RJTUUH5QQMAxcTtnBC+AAAAZNJREFUGNNj4OFh4OXj5xcQFGLggQEgi1FYRFRUTFwCKsjAwMTAwCwpJZ2amiYjK8cCFGZglVdQZFBSVklNz8jIyFRVU9dgY1PS1MrKZtDWycnNy88vKNTVK9I3MDQyLi4pZTAxLSuvqKyqrqmtqzczN7GwbGgsZShtam5pbW1ta2svzOjobOrq7untY+ifMHHS5CmTp06bPmPmrIyMhtlz5vYx9M2bvwCkcuGixUumLF22fMXKVf0M/avXrK2qqlq8bv2GjZuWbN6ydc02oPbtO3buys/fvWfv+vZ9+9ev33DgIFD7oQWHgc7MOHL02ObjU07UnNx4qpSh//SZjrTU1LPnzl+4uP7SyWM1lzuvMJR21V+9dv36jZu3yjL2rL29887de/cZSh88tLK2sbG1s39U9/jJk6fPnjtYMzg6vXB2cXVz9/B8+ep1Rvqbt++8XBi8fXz9/NmZ2AM8At9/+Pjx0+egYH8G/5BQDlBIcoaFR0R++RoVHcPBAAKwwOWKjYtPSOQGhzwiFpKSk5NTgCIAn+ukv+ne1I0AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjEtMDQtMTJUMDM6MjM6MTkrMDA6MDClecqxAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDIxLTA0LTEyVDAzOjIzOjE5KzAwOjAw1CRyDQAAAABJRU5ErkJggg==
asSource: false
asTarget: true
uploadPath: /upload.php
search: 
  path: /torrents.php
  params:
    searchstr: '{name}'
    order_by: s4
    order_way: desc
    disablegrouping: 1
name:
  selector: '#title'
description:
  selector: '#desc'
category: 
  selector: '#categories'
  map: 
    movie: 'Movies'
    tv: 'TV'
    tvPack: 'TV'
    documentary: 'Movies'
    cartoon: 'Anime'
    app: 'Applications'
    ebook: 'E-Books'
    magazine: 'Magazines'
    audioBook: 'Audiobooks'
    comics: 'Comics'
source: 
  selector: 'select[name="source"]'
  map:
    uhdbluray: 'BluRay'
    bluray: 'BluRay'
    hdtv: 'HDTV'
    dvd: 'DVD9'
    web: 'WEB-DL'
    webrip: 'WebRip'
    vhs: 'VHSRip'
    hddvd: 'HD-DVD'
    bluray3d: 'BluRay 3D'
videoCodec:
  selector: 'select[name="videoformat"]'
  map:
    h264: 'H.264'
    hevc: 'H.265'
    x264: 'x264'
    x265: 'x265'
    h265: 'H.265'
    mpeg2: 'MPEG-2'
    mpeg4: 'H.264'
    vc1: 'VC-1'
    xvid: 'XVid'
    dvd: 'MPEG-2'
audioCodec:
  selector: 'select[name="audioformat"]'
  map:
    aac: 'AAC'
    ac3: 'AC-3'
    dd: 'AC-3'
    dd+: 'AC-3'
    dts: 'DTS'
    truehd: 'True-HD'
    lpcm: 'PCM'
    flac: 'FLAC'
    dtshdma: 'DTS-HD'
    atmos: 'Dolby Atmos'
    dtsx: 'DTS:X'
    mp3: 'MP3'
format: 
  selector: 'select[name="container"]'
  map:
    mkv: 'MKV'
    mp4: 'MP4'
    avi: 'AVI'
    ts: 'TS'
    wmv: 'WMV'
    vob: 'VOB'
    m2ts: 'm2ts'
resolution:
  selector: 'select[name="resolution"]'
  map:
    2160p: '2160p'
    1080p: '1080p'
    1080i: '1080i'
    720p: '720p'
    480p: '480p'
    480i: '480i'
    other: 'SD'
mediaInfo:
  selector: '#release_desc'
poster: 
  selector: '#image'
year: 
  selector: 'input[name="year"]'
tags: 
  selector: '#tags'